files:
  include: 'source/stylesheets/*'

rules:
  extends-before-mixins: 2

  extends-before-declarations: 2

  placeholder-in-extend: 2

  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  hex-notation:
    - 2
    -
      style: uppercase

  indentation:
    - 2
    -
      size: 2

  property-sort-order:
    - 0

  class-name-format:
    - 2
    -
      convention: hyphenatedbem

  no-color-literals:
    - 0
